export { HomePage } from "./HomePage";
export { AboutPage } from "./AboutPage";
export { ClientsPage } from "./ClientsPage";
export { ContactPage } from "./ContactPage";
export { BlogPage } from "./BlogPage";
export { CareersPage } from "./CareersPage";
export { CommunityPage } from "./CommunityPage";
export { ExpertisePage } from "./ExpertisePage";
export { IndustriesPageComponent as IndustriesPage } from "./IndustriesPage";
export { InsightsDetailPageComponent as InsightsDetailPage } from "./InsightsDetailPage";
export { InsightsPageComponent as InsightsPage } from "./InsightsPage";
export { ProcessPageComponent as ProcessPage } from "./ProcessPage";
export { ServiceDetailPageComponent as ServiceDetailPage } from "./ServiceDetailPage";
export { ServicesPageComponent as ServicesPage } from "./ServicesPage";
export { WorkDetailPageComponent as WorkDetailPage } from "./WorkDetailPage";
export { WorkPageComponent as WorkPage } from "./WorkPage";
